# Generated by Django 5.1.7 on 2025-11-22 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysisresult',
            options={'ordering': ['-created_at'], 'verbose_name': 'Plant Analysis', 'verbose_name_plural': 'Plant Analyses'},
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='confidence_score',
            field=models.FloatField(blank=True, help_text='Confidence score (0-1)', null=True),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='disease_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='recommendations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='image',
            field=models.ImageField(upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='result',
            field=models.JSONField(blank=True, help_text='Full ML model output', null=True),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
