# Generated by Django 5.1.7 on 2025-11-22 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_analysisresult_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='image_hash',
            field=models.CharField(blank=True, help_text='SHA-256 hash of the original image for integrity check', max_length=64, null=True),
        ),
    ]
