# Generated by Django 5.1.7 on 2025-11-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_analysisresult_image_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='digital_signature',
            field=models.TextField(blank=True, help_text='Digital signature of the image', null=True),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='public_key',
            field=models.TextField(blank=True, help_text='Public key used for signature verification', null=True),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='signature_verified',
            field=models.BooleanField(default=False, help_text='Whether the digital signature was verified'),
        ),
    ]
